model_file: /home/stfn/recognition_database/models/can/can_model.pcd


### opti_result_hs_2015_02_01_17_49.txt
# nice ...

aligner_numberOfSamples: 3
aligner_correspondenceRandomness: 50
aligner_similarityThreshold: 0.53277
aligner_maxCorrespondenceDistanceMultiplier: 0.71790
aligner_inlierFraction: 0.32941
aligner_maximumIterations: 50000
#aligner_vg_leafSize: -0.08532
aligner_nest_radius: 0.261373
aligner_fest_radius: -0.02672
