num_trees: 15
patch_widht: 10
patch_height: 10
kernel_smooth: 21
kernel_vote: 20
kernel_sigma: 2
threshold_hierarchy: 1.0
max_candidates: 20
detection_threshold: 0.1
do_backprojection: true
cand_max_width: 320
cand_max_height: 240