number_of_trees: 15
p_widht: 10
p_height: 10
tree_max_depth: 25
image_scale: 0.7
subsample_models: -1
subsample_backgrounds: -1
patches_per_model_image: 100
patches_per_background_image: 250

database_path: '/home/stfn/recognition_database'
tree_file_prefix: 'treetable_'
forest_id: 'huiii'

models: ['barrel','block']
backgrounds: ['spacebot_bg']